# Generated by Django 5.1.3 on 2025-05-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_type',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='page_number',
        ),
        migrations.AddField(
            model_name='annotation',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('highlight', 'Highlight'), ('comment', 'Comment'), ('drawing', 'Drawing')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='documents.documentversion'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
